<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert(array_map(function ($row) {
            $date = new DateTime('now', new DateTimeZone('UTC'));
            $row['created_at'] = $date;
            $row['updated_at'] = $date;
            return $row;
        }, [
            ["region_code"=>"AF", "name"=> "Afghanistan"],
            ["region_code"=>"AX", "name"=> "Åland Islands"],
            ["region_code"=>"AL", "name"=> "Albania"],
            ["region_code"=>"DZ", "name"=> "Algeria"],
            ["region_code"=>"AS", "name"=> "American Samoa"],
            ["region_code"=>"AD", "name"=> "Andorra"],
            ["region_code"=>"AO", "name"=> "Angola"],
            ["region_code"=>"AI", "name"=> "Anguilla"],
            ["region_code"=>"AG", "name"=> "Antigua and Barbuda"],
            ["region_code"=>"AR", "name"=> "Argentina"],
            ["region_code"=>"AM", "name"=> "Armenia"],
            ["region_code"=>"AW", "name"=> "Aruba"],
            ["region_code"=>"AU", "name"=> "Australia"],
            ["region_code"=>"AT", "name"=> "Austria"],
            ["region_code"=>"AZ", "name"=> "Azerbaijan"],
            ["region_code"=>"BS", "name"=> "Bahamas"],
            ["region_code"=>"BH", "name"=> "Bahrain"],
            ["region_code"=>"BD", "name"=> "Bangladesh"],
            ["region_code"=>"BB", "name"=> "Barbados"],
            ["region_code"=>"BY", "name"=> "Belarus"],
            ["region_code"=>"BE", "name"=> "Belgium"],
            ["region_code"=>"BZ", "name"=> "Belize"],
            ["region_code"=>"BJ", "name"=> "Benin"],
            ["region_code"=>"BM", "name"=> "Bermuda"],
            ["region_code"=>"BT", "name"=> "Bhutan"],
            ["region_code"=>"BO", "name"=> "Bolivia"],
            ["region_code"=>"BA", "name"=> "Bosnia and Herzegovina"],
            ["region_code"=>"BW", "name"=> "Botswana"],
            ["region_code"=>"BV", "name"=> "Bouvet Island"],
            ["region_code"=>"BR", "name"=> "Brazil"],
            ["region_code"=>"IO", "name"=> "British Indian Ocean Territory"],
            ["region_code"=>"VG", "name"=> "British Virgin Islands"],
            ["region_code"=>"BN", "name"=> "Brunei"],
            ["region_code"=>"BG", "name"=> "Bulgaria"],
            ["region_code"=>"BF", "name"=> "Burkina Faso"],
            ["region_code"=>"BI", "name"=> "Burundi"],
            ["region_code"=>"KH", "name"=> "Cambodia"],
            ["region_code"=>"CM", "name"=> "Cameroon"],
            ["region_code"=>"CV", "name"=> "Cape Verde"],
            ["region_code"=>"KY", "name"=> "Cayman Islands"],
            ["region_code"=>"CF", "name"=> "Central African Republic"],
            ["region_code"=>"TD", "name"=> "Chad"],
            ["region_code"=>"CL", "name"=> "Chile"],
            ["region_code"=>"CN", "name"=> "China"],
            ["region_code"=>"CX", "name"=> "Christmas Island"],
            ["region_code"=>"CC", "name"=> "Cocos (Keeling) Islands"],
            ["region_code"=>"CO", "name"=> "Colombia"],
            ["region_code"=>"KM", "name"=> "Comoros"],
            ["region_code"=>"CG", "name"=> "Congo, Republic of"],
            ["region_code"=>"CK", "name"=> "Cook Islands"],
            ["region_code"=>"CR", "name"=> "Costa Rica"],
            ["region_code"=>"HR", "name"=> "Croatia"],
            ["region_code"=>"CW", "name"=> "Curaçao"],
            ["region_code"=>"CY", "name"=> "Cyprus"],
            ["region_code"=>"CZ", "name"=> "Czech Republic"],
            ["region_code"=>"DK", "name"=> "Denmark"],
            ["region_code"=>"DJ", "name"=> "Djibouti"],
            ["region_code"=>"DM", "name"=> "Dominica"],
            ["region_code"=>"DO", "name"=> "Dominican Republic"],
            ["region_code"=>"EC", "name"=> "Ecuador"],
            ["region_code"=>"EG", "name"=> "Egypt"],
            ["region_code"=>"SV", "name"=> "El Salvador"],
            ["region_code"=>"GQ", "name"=> "Equatorial Guinea"],
            ["region_code"=>"ER", "name"=> "Eritrea"],
            ["region_code"=>"EE", "name"=> "Estonia"],
            ["region_code"=>"ET", "name"=> "Ethiopia"],
            ["region_code"=>"FK", "name"=> "Falkland Islands (Malvinas)"],
            ["region_code"=>"FO", "name"=> "Faroe Islands"],
            ["region_code"=>"FJ", "name"=> "Fiji"],
            ["region_code"=>"FI", "name"=> "Finland"],
            ["region_code"=>"FR", "name"=> "France"],
            ["region_code"=>"GF", "name"=> "French Guiana"],
            ["region_code"=>"PF", "name"=> "French Polynesia"],
            ["region_code"=>"TF", "name"=> "French Southern Territories"],
            ["region_code"=>"GA", "name"=> "Gabon"],
            ["region_code"=>"GM", "name"=> "Gambia"],
            ["region_code"=>"GE", "name"=> "Georgia"],
            ["region_code"=>"DE", "name"=> "Germany"],
            ["region_code"=>"GH", "name"=> "Ghana"],
            ["region_code"=>"GI", "name"=> "Gibraltar"],
            ["region_code"=>"GR", "name"=> "Greece"],
            ["region_code"=>"GL", "name"=> "Greenland"],
            ["region_code"=>"GD", "name"=> "Grenada"],
            ["region_code"=>"GP", "name"=> "Guadeloupe"],
            ["region_code"=>"GU", "name"=> "Guam"],
            ["region_code"=>"GT", "name"=> "Guatemala"],
            ["region_code"=>"GG", "name"=> "Guernsey"],
            ["region_code"=>"GN", "name"=> "Guinea"],
            ["region_code"=>"GW", "name"=> "Guinea-Bissau"],
            ["region_code"=>"GY", "name"=> "Guyana"],
            ["region_code"=>"HT", "name"=> "Haiti"],
            ["region_code"=>"HM", "name"=> "Heard Island and McDonald Islands"],
            ["region_code"=>"VA", "name"=> "Holy See (Vatican City State)"],
            ["region_code"=>"HN", "name"=> "Honduras"],
            ["region_code"=>"HK", "name"=> "Hong Kong"],
            ["region_code"=>"HU", "name"=> "Hungary"],
            ["region_code"=>"IS", "name"=> "Iceland"],
            ["region_code"=>"IN", "name"=> "India"],
            ["region_code"=>"ID", "name"=> "Indonesia"],
            ["region_code"=>"IQ", "name"=> "Iraq"],
            ["region_code"=>"IE", "name"=> "Ireland"],
            ["region_code"=>"IM", "name"=> "Isle of Man"],
            ["region_code"=>"IL", "name"=> "Israel"],
            ["region_code"=>"IT", "name"=> "Italy"],
            ["region_code"=>"IC", "name"=> "Ivory Coast"],
            ["region_code"=>"JM", "name"=> "Jamaica"],
            ["region_code"=>"JP", "name"=> "Japan"],
            ["region_code"=>"JE", "name"=> "Jersey"],
            ["region_code"=>"JO", "name"=> "Jordan"],
            ["region_code"=>"KZ", "name"=> "Kazakhstan"],
            ["region_code"=>"KE", "name"=> "Kenya"],
            ["region_code"=>"KI", "name"=> "Kiribati"],
            ["region_code"=>"KV", "name"=> "Kosovo"],
            ["region_code"=>"KW", "name"=> "Kuwait"],
            ["region_code"=>"KG", "name"=> "Kyrgyzstan"],
            ["region_code"=>"LA", "name"=> "Laos"],
            ["region_code"=>"LV", "name"=> "Latvia"],
            ["region_code"=>"LB", "name"=> "Lebanon"],
            ["region_code"=>"LS", "name"=> "Lesotho"],
            ["region_code"=>"LR", "name"=> "Liberia"],
            ["region_code"=>"LY", "name"=> "Libya"],
            ["region_code"=>"LI", "name"=> "Liechtenstein"],
            ["region_code"=>"LT", "name"=> "Lithuania"],
            ["region_code"=>"LU", "name"=> "Luxembourg"],
            ["region_code"=>"MO", "name"=> "Macao"],
            ["region_code"=>"MK", "name"=> "Macedonia"],
            ["region_code"=>"MG", "name"=> "Madagascar"],
            ["region_code"=>"MW", "name"=> "Malawi"],
            ["region_code"=>"MY", "name"=> "Malaysia"],
            ["region_code"=>"MV", "name"=> "Maldives"],
            ["region_code"=>"ML", "name"=> "Mali"],
            ["region_code"=>"MT", "name"=> "Malta"],
            ["region_code"=>"MH", "name"=> "Marshall Islands"],
            ["region_code"=>"MQ", "name"=> "Martinique"],
            ["region_code"=>"MR", "name"=> "Mauritania"],
            ["region_code"=>"MU", "name"=> "Mauritius"],
            ["region_code"=>"YT", "name"=> "Mayotte"],
            ["region_code"=>"MX", "name"=> "Mexico"],
            ["region_code"=>"FM", "name"=> "Micronesia, Federated States of"],
            ["region_code"=>"MD", "name"=> "Moldova"],
            ["region_code"=>"MC", "name"=> "Monaco"],
            ["region_code"=>"MN", "name"=> "Mongolia"],
            ["region_code"=>"ME", "name"=> "Montenegro"],
            ["region_code"=>"MS", "name"=> "Montserrat"],
            ["region_code"=>"MA", "name"=> "Morocco"],
            ["region_code"=>"MZ", "name"=> "Mozambique"],
            ["region_code"=>"MM", "name"=> "Myanmar (Burma)"],
            ["region_code"=>"NA", "name"=> "Namibia"],
            ["region_code"=>"NR", "name"=> "Nauru"],
            ["region_code"=>"NP", "name"=> "Nepal"],
            ["region_code"=>"AN", "name"=> "Netherlands Antilles"],
            ["region_code"=>"NC", "name"=> "New Caledonia"],
            ["region_code"=>"NZ", "name"=> "New Zealand"],
            ["region_code"=>"NI", "name"=> "Nicaragua"],
            ["region_code"=>"NE", "name"=> "Niger"],
            ["region_code"=>"NG", "name"=> "Nigeria"],
            ["region_code"=>"NU", "name"=> "Niue"],
            ["region_code"=>"NF", "name"=> "Norfolk Island"],
            ["region_code"=>"MP", "name"=> "Northern Mariana Islands"],
            ["region_code"=>"NO", "name"=> "Norway"],
            ["region_code"=>"OM", "name"=> "Oman"],
            ["region_code"=>"PK", "name"=> "Pakistan"],
            ["region_code"=>"PW", "name"=> "Palau"],
            ["region_code"=>"PS", "name"=> "Palestine, State of" ],
            ["region_code"=>"PA", "name"=> "Panama"],
            ["region_code"=>"PG", "name"=> "Papua New Guinea"],
            ["region_code"=>"PY", "name"=> "Paraguay"],
            ["region_code"=>"PE", "name"=> "Peru"],
            ["region_code"=>"PH", "name"=> "Philippines"],
            ["region_code"=>"PL", "name"=> "Poland"],
            ["region_code"=>"PT", "name"=> "Portugal"],
            ["region_code"=>"PR", "name"=> "Puerto Rico"],
            ["region_code"=>"QA", "name"=> "Qatar"],
            ["region_code"=>"RE", "name"=> "Reunion"],
            ["region_code"=>"RO", "name"=> "Romania"],
            ["region_code"=>"RU", "name"=> "Russia"],
            ["region_code"=>"RW", "name"=> "Rwanda"],
            ["region_code"=>"BL", "name"=> "Saint Barthélemy"],
            ["region_code"=>"SH", "name"=> "Saint Helena"],
            ["region_code"=>"KN", "name"=> "Saint Kitts and Nevis"],
            ["region_code"=>"LC", "name"=> "Saint Lucia"],
            ["region_code"=>"MF", "name"=> "Saint Martin (French part)"],
            ["region_code"=>"PM", "name"=> "Saint Pierre and Miquelon"],
            ["region_code"=>"VC", "name"=> "Saint Vincent and the Grenadines"],
            ["region_code"=>"WS", "name"=> "Samoa"],
            ["region_code"=>"SM", "name"=> "San Marino"],
            ["region_code"=>"ST", "name"=> "Sao Tome and Principe"],
            ["region_code"=>"SA", "name"=> "Saudi Arabia"],
            ["region_code"=>"SN", "name"=> "Senegal"],
            ["region_code"=>"RS", "name"=> "Serbia"],
            ["region_code"=>"SC", "name"=> "Seychelles"],
            ["region_code"=>"SL", "name"=> "Sierra Leone"],
            ["region_code"=>"SG", "name"=> "Singapore"],
            ["region_code"=>"SX", "name"=> "Sint Maarten (Dutch part)"],
            ["region_code"=>"SK", "name"=> "Slovakia"],
            ["region_code"=>"SI", "name"=> "Slovenia"],
            ["region_code"=>"SB", "name"=> "Solomon Islands"],
            ["region_code"=>"SO", "name"=> "Somalia"],
            ["region_code"=>"ZA", "name"=> "South Africa"],
            ["region_code"=>"GS", "name"=> "South Georgia and the South Sandwich Islands"],
            ["region_code"=>"KR", "name"=> "South Korea"],
            ["region_code"=>"SS", "name"=> "South Sudan"],
            ["region_code"=>"ES", "name"=> "Spain"],
            ["region_code"=>"LK", "name"=> "Sri Lanka"],
            ["region_code"=>"SD", "name"=> "Sudan"],
            ["region_code"=>"SR", "name"=> "Suriname"],
            ["region_code"=>"SJ", "name"=> "Svalbard and Jan Mayen"],
            ["region_code"=>"SZ", "name"=> "Swaziland"],
            ["region_code"=>"SE", "name"=> "Sweden"],
            ["region_code"=>"CH", "name"=> "Switzerland"],
            ["region_code"=>"TW", "name"=> "Taiwan"],
            ["region_code"=>"TJ", "name"=> "Tajikistan"],
            ["region_code"=>"TZ", "name"=> "Tanzania"],
            ["region_code"=>"TH", "name"=> "Thailand"],
            ["region_code"=>"NL", "name"=> "The Netherlands"],
            ["region_code"=>"TL", "name"=> "Timor-Leste"],
            ["region_code"=>"TG", "name"=> "Togo"],
            ["region_code"=>"TK", "name"=> "Tokelau"],
            ["region_code"=>"TO", "name"=> "Tonga"],
            ["region_code"=>"TT", "name"=> "Trinidad"],
            ["region_code"=>"TN", "name"=> "Tunisia"],
            ["region_code"=>"TR", "name"=> "Turkey"],
            ["region_code"=>"TM", "name"=> "Turkmenistan"],
            ["region_code"=>"TC", "name"=> "Turks and Caicos Islands"],
            ["region_code"=>"TV", "name"=> "Tuvalu"],
            ["region_code"=>"UG", "name"=> "Uganda"],
            ["region_code"=>"UA", "name"=> "Ukraine"],
            ["region_code"=>"AE", "name"=> "United Arab Emirates"],
            ["region_code"=>"GB", "name"=> "United Kingdom"],
            ["region_code"=>"US", "name"=> "United States"],
            ["region_code"=>"UM", "name"=> "United States Minor Outlying Islands"],
            ["region_code"=>"UY", "name"=> "Uruguay"],
            ["region_code"=>"VI", "name"=> "U.S. Virgin Islands"],
            ["region_code"=>"UZ", "name"=> "Uzbekistan"],
            ["region_code"=>"VU", "name"=> "Vanuatu"],
            ["region_code"=>"VE", "name"=> "Venezuela"],
            ["region_code"=>"VN", "name"=> "Vietnam"],
            ["region_code"=>"WF", "name"=> "Wallis and Futuna"],
            ["region_code"=>"EH", "name"=> "Western Sahara"],
            ["region_code"=>"YE", "name"=> "Yemen"],
            ["region_code"=>"CD", "name"=> "Zaire (Democratic Republic of Congo)"],
            ["region_code"=>"ZM", "name"=> "Zambia"],
            ["region_code"=>"ZW", "name"=> "Zimbabwe"],
        ]));
    }
}
